In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
Orders = pd.read_excel('../data/raw/Muesli Project raw data.xlsx',sheet_name='Orders', header = 1)

In [4]:
Orders.head(5)

,Index,Order ID,Order Date,Ship Mode,Customer ID,Customer Name,Origin Channel,Country/Region,City,State,Postal Code,Region,Category,Sub-Category,Product ID,Sales,Quantity,Discount,Profit
0,27,CA-2019-121755,2019-01-16,Second Class,EH-13945,Eric Hoffmann,Email,United States,Los Angeles,California,90049.0,West,Special Projects Muesil,Gluten Free,TEC-AC-10003027,90.57,3,0.0,11.7741
1,45,CA-2019-118255,2019-03-11,First Class,ON-18715,Odella Nelson,Sales,United States,Eagan,Minnesota,55122.0,Central,Special Projects Muesil,Gluten Free,TEC-AC-10000171,45.98,2,0.0,19.7714
2,48,CA-2019-169194,2019-06-20,Standard Class,LH-16900,Lena Hernandez,Email,United States,Dover,Delaware,19901.0,East,Special Projects Muesil,Gluten Free,TEC-AC-10002167,45.00,3,0.0,4.9500
3,60,CA-2019-111682,2019-06-17,First Class,TB-21055,Ted Butterfield,Email,United States,Troy,New York,12180.0,East,Special Projects Muesil,Gluten Free,TEC-AC-10002167,30.00,2,0.0,3.3000
4,63,CA-2018-135545,2018-11-24,Standard Class,KM-16720,Kunst Miller,Email,United States,Los Angeles,California,90004.0,West,Special Projects Muesil,Gluten Free,TEC-AC-10004633,13.98,2,0.0,6.1512

#There is a header, but it does not in currect place!

In [5]:
Orders.columns

Index(['Index', 'Order ID', 'Order Date', 'Ship Mode', 'Customer ID',
       'Customer Name', 'Origin Channel', 'Country/Region', 'City', 'State',
       'Postal Code', 'Region', 'Category', 'Sub-Category', 'Product ID',
       'Sales', 'Quantity', 'Discount', 'Profit'],
      dtype='str')

In [6]:
Orders.head(10)

,Index,Order ID,Order Date,Ship Mode,Customer ID,Customer Name,Origin Channel,Country/Region,City,State,Postal Code,Region,Category,Sub-Category,Product ID,Sales,Quantity,Discount,Profit
0,27,CA-2019-121755,2019-01-16,Second Class,EH-13945,Eric Hoffmann,Email,United States,Los Angeles,California,90049.0,West,Special Projects Muesil,Gluten Free,TEC-AC-10003027,90.570,3,0.0,11.7741
1,45,CA-2019-118255,2019-03-11,First Class,ON-18715,Odella Nelson,Sales,United States,Eagan,Minnesota,55122.0,Central,Special Projects Muesil,Gluten Free,TEC-AC-10000171,45.980,2,0.0,19.7714
2,48,CA-2019-169194,2019-06-20,Standard Class,LH-16900,Lena Hernandez,Email,United States,Dover,Delaware,19901.0,East,Special Projects Muesil,Gluten Free,TEC-AC-10002167,45.000,3,0.0,4.9500
3,60,CA-2019-111682,2019-06-17,First Class,TB-21055,Ted Butterfield,Email,United States,Troy,New York,12180.0,East,Special Projects Muesil,Gluten Free,TEC-AC-10002167,30.000,2,0.0,3.3000
4,63,CA-2018-135545,2018-11-24,Standard Class,KM-16720,Kunst Miller,Email,United States,Los Angeles,California,90004.0,West,Special Projects Muesil,Gluten Free,TEC-AC-10004633,13.980,2,0.0,6.1512
5,87,CA-2020-155558,2020-10-26,Standard Class,PG-18895,Paul Gonzalez,Email,United States,Rochester,Minnesota,55901.0,Central,Special Projects Muesil,Gluten Free,TEC-AC-10001998,19.990,1,0.0,6.7966
6,101,CA-2019-158568,2019-08-29,Standard Class,RB-19465,Rick Bensley,Facebook,United States,Chicago,Illinois,60610.0,Central,Special Projects Muesil,Gluten Free,TEC-AC-10001767,95.976,3,0.2,-10.7973
7,104,US-2018-156867,2018-11-13,Standard Class,LC-16870,Lena Cacioppo,Email,United States,Aurora,Colorado,80013.0,West,Special Projects Muesil,Gluten Free,TEC-AC-10001552,238.896,6,0.2,-26.8758
8,107,CA-2020-119004,2020-11-23,Standard Class,JM-15250,Janet Martin,Email,United States,Charlotte,North Carolina,28205.0,South,Special Projects Muesil,Gluten Free,TEC-AC-10003499,74.112,8,0.2,17.6016
9,110,CA-2018-129476,2018-10-15,Standard Class,PA-19060,Pete Armstrong,Facebook,United States,Orland Park,Illinois,60462.0,Central,Special Projects Muesil,Gluten Free,TEC-AC-10000844,339.960,5,0.2,67.9920

In [7]:
Orders.shape

(9994, 19)

In [8]:
Orders.info()

<class 'pandas.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 19 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Index           9994 non-null   int64
 1   Order ID        9994 non-null   str
 2   Order Date      9994 non-null   datetime64[us]
 3   Ship Mode       9994 non-null   str
 4   Customer ID     9994 non-null   str
 5   Customer Name   9994 non-null   str
 6   Origin Channel  9994 non-null   str
 7   Country/Region  9994 non-null   str
 8   City            9994 non-null   str
 9   State           9994 non-null   str
 10  Postal Code     9983 non-null   float64
 11  Region          9994 non-null   str
 12  Category        9994 non-null   str
 13  Sub-Category    9994 non-null   str
 14  Product ID      9994 non-null   str
 15  Sales           9994 non-null   float64
 16  Quantity        9994 non-null   int64
 17  Discount        9994 non-null   float64
 18  Profit          9994 non-null   float64
dtypes: datetime64[us](1), float64(4), int64(2), str(12)
memory usage: 1.4 MB

In [9]:
Orders.columns

Index(['Index', 'Order ID', 'Order Date', 'Ship Mode', 'Customer ID',
       'Customer Name', 'Origin Channel', 'Country/Region', 'City', 'State',
       'Postal Code', 'Region', 'Category', 'Sub-Category', 'Product ID',
       'Sales', 'Quantity', 'Discount', 'Profit'],
      dtype='str')

In [10]:
Orders[['Order ID','Ship Mode', 'Customer ID', 'Origin Channel', 'Country/Region', 'City', 'State','Region', 'Category', 'Sub-Category', 'Product ID']].describe()

,Order ID,Ship Mode,Customer ID,Origin Channel,Country/Region,City,State,Region,Category,Sub-Category,Product ID
count,9994,9994,9994,9994,9994,9994,9994,9994,9994,9994,9994
unique,5009,3,793,3,1,531,49,4,3,17,1862
top,CA-2020-100111,Standard Class,WB-21850,Email,United States,New York City,California,West,Power Muesli,Super Fibre Boost,OFF-PA-10001970
freq,14,5968,37,5191,9994,915,2001,3203,6026,1523,19

In [11]:
Orders[['Sales', 'Quantity', 'Discount', 'Profit']].describe()

              Sales     Quantity     Discount       Profit
count   9994.000000  9994.000000  9994.000000  9994.000000
mean     229.858001     3.789574     0.156203    28.656896
std      623.245101     2.225110     0.206452   234.260108
min        0.444000     1.000000     0.000000 -6599.978000
25%       17.280000     2.000000     0.000000     1.728750
50%       54.490000     3.000000     0.200000     8.666500
75%      209.940000     5.000000     0.200000    29.364000
max    22638.480000    14.000000     0.800000  8399.976000

In [12]:
Orders.isna().sum().sort_values(ascending=False)

Postal Code       11
Index              0
Discount           0
Quantity           0
Sales              0
Product ID         0
Sub-Category       0
Category           0
Region             0
State              0
Order ID           0
City               0
Country/Region     0
Origin Channel     0
Customer Name      0
Customer ID        0
Ship Mode          0
Order Date         0
Profit             0
dtype: int64

In [13]:
Orders.duplicated().sum()

np.int64(0)

1- there is 11 None value on 'Postal Code' (dealing with missing value)
2- No duplicate values
3- data type are currect
4- check out of line values
5- data bining
6- turning categorical to numerical

In [14]:
campaign_date = pd.read_excel('../data/raw/Muesli Project raw data.xlsx',sheet_name='Campaign Data')

In [15]:
campaign_date.head(10)

         Order ID Arrival Scan Date     Customer Name
0  CA-2019-109666        2019-05-03      Kunst Miller
1  CA-2019-138933        2019-05-03       Jack Lebron
2  CA-2019-130001        2019-05-03  Heather Kirkland
3  CA-2019-113061        2019-05-06         Ed Ludwig
4  CA-2019-162138        2019-05-06       Grace Kelly
5  CA-2019-126270        2019-05-06      Art Ferguson
6  CA-2019-168081        2019-05-06   Cathy Armstrong
7  CA-2019-149279        2019-05-06      Craig Leslie
8  CA-2019-146836        2019-05-06     Cindy Chapman
9  CA-2019-109869        2019-05-07     Tanja Norvell

In [16]:
campaign_date.columns

Index(['Order ID', 'Arrival Scan Date', 'Customer Name'], dtype='str')

In [17]:
campaign_date.info()

<class 'pandas.DataFrame'>
RangeIndex: 333 entries, 0 to 332
Data columns (total 3 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Order ID           333 non-null    str
 1   Arrival Scan Date  333 non-null    datetime64[us]
 2   Customer Name      333 non-null    str
dtypes: datetime64[us](1), str(2)
memory usage: 7.9 KB

In [18]:
campaign_date.describe()

                Arrival Scan Date
count                         333
mean   2019-10-14 19:36:12.972973
min           2019-05-03 00:00:00
25%           2019-09-09 00:00:00
50%           2019-10-21 00:00:00
75%           2019-12-16 00:00:00
max           2020-05-15 00:00:00

In [19]:
campaign_date.shape

(333, 3)

In [20]:
campaign_date.isna().sum().sort_values(ascending=False)

Order ID             0
Arrival Scan Date    0
Customer Name        0
dtype: int64

In [21]:
campaign_date.duplicated().sum()

np.int64(0)

In [22]:
order_process_data = pd.read_excel('../data/raw/Muesli Project raw data.xlsx',sheet_name='Order Process Data')

In [23]:
order_process_data.head()

   Row ID        Order ID Order Date On Truck Scan Date            Ship Mode
0    3074  CA-2019-125206 2019-01-03         2019-01-07              Express
1    4919  CA-2019-160304 2019-01-02         2019-01-09  Standard Processing
2    4920  CA-2019-160304 2019-01-02         2019-01-09  Standard Processing
3    8604  US-2019-116365 2019-01-03         2019-01-09  Standard Processing
4    8605  US-2019-116365 2019-01-03         2019-01-09  Standard Processing

In [24]:
order_process_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 5899 entries, 0 to 5898
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Row ID              5899 non-null   int64
 1   Order ID            5899 non-null   str
 2   Order Date          5899 non-null   datetime64[us]
 3   On Truck Scan Date  5899 non-null   datetime64[us]
 4   Ship Mode           5899 non-null   str
dtypes: datetime64[us](2), int64(1), str(2)
memory usage: 230.6 KB

In [25]:
order_process_data.shape

(5899, 5)

In [26]:
order_process_data.describe(include='all')

,Row ID,Order ID,Order Date,On Truck Scan Date,Ship Mode
count,5899.000000,5899,5899,5899,5899
unique,NaN,3002,NaN,NaN,2
top,NaN,CA-2020-100111,NaN,NaN,Standard Processing
freq,NaN,14,NaN,NaN,4596
mean,5022.428208,NaN,2020-02-29 02:22:48.231903,2020-03-06 05:16:21.929140,NaN
min,1.000000,NaN,2019-01-02 00:00:00,2019-01-07 00:00:00,NaN
25%,2485.500000,NaN,2019-09-11 00:00:00,2019-09-18 00:00:00,NaN
50%,5091.000000,NaN,2020-03-16 00:00:00,2020-03-20 00:00:00,NaN
75%,7460.000000,NaN,2020-09-13 12:00:00,2020-09-18 00:00:00,NaN
max,9994.000000,NaN,2020-12-30 00:00:00,2021-01-06 00:00:00,NaN
std,2878.464633,NaN,NaN,NaN,NaN

In [27]:
order_process_data.columns

Index(['Row ID', 'Order ID', 'Order Date', 'On Truck Scan Date', 'Ship Mode'], dtype='str')

In [28]:
order_process_data.isna().sum().sort_values(ascending=False)

Row ID                0
Order ID              0
Order Date            0
On Truck Scan Date    0
Ship Mode             0
dtype: int64

In [29]:
order_process_data.duplicated().sum()

np.int64(0)

In [30]:
InternData_study = pd.read_excel('../data/raw/Muesli Project raw data.xlsx',sheet_name='InternData Study')

In [31]:
InternData_study.head()

         Order ID Ready to Ship Date Pickup Date
0  CA-2019-116540         2019-09-02  2019-09-03
1  CA-2019-116540         2019-09-02  2019-09-03
2  CA-2019-129847         2019-09-04  2019-09-04
3  CA-2019-129630         2019-09-04  2019-09-04
4  CA-2019-106278         2019-09-05  2019-09-06

In [32]:
InternData_study.info()

<class 'pandas.DataFrame'>
RangeIndex: 290 entries, 0 to 289
Data columns (total 3 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Order ID            290 non-null    str
 1   Ready to Ship Date  290 non-null    datetime64[us]
 2   Pickup Date         290 non-null    datetime64[us]
dtypes: datetime64[us](2), str(1)
memory usage: 6.9 KB

In [33]:
InternData_study.shape

(290, 3)

In [34]:
InternData_study.columns

Index(['Order ID', 'Ready to Ship Date', 'Pickup Date'], dtype='str')

In [35]:
InternData_study.describe()

               Ready to Ship Date                 Pickup Date
count                         290                         290
mean   2020-06-18 15:08:41.379310  2020-06-20 06:47:10.344827
min           2019-09-02 00:00:00         2019-09-03 00:00:00
25%           2019-09-23 00:00:00         2019-09-23 12:00:00
50%           2020-11-10 00:00:00         2020-11-12 00:00:00
75%           2020-11-23 00:00:00         2020-11-23 00:00:00
max           2020-12-07 00:00:00         2020-12-09 00:00:00

In [36]:
InternData_study.isna().sum().sort_values(ascending=False)

Order ID              0
Ready to Ship Date    0
Pickup Date           0
dtype: int64

In [37]:
InternData_study.duplicated().sum()

np.int64(86)

Cleaning data:
    1- Handling missing data - repititive rows
    2- Data formating
    3- data normalization(centering and scaling)
    4- data binning
    5- turning categorical to numerical variebles

create new columns belong to our KPIs