In [1]:
import pandas as pd
import numpy as np

In [4]:
order_process_data = pd.read_excel('../data/raw/Muesli Project raw data.xlsx',sheet_name='Order Process Data')

In [5]:
order_process_data.head(4)

   Row ID        Order ID Order Date On Truck Scan Date            Ship Mode
0    3074  CA-2019-125206 2019-01-03         2019-01-07              Express
1    4919  CA-2019-160304 2019-01-02         2019-01-09  Standard Processing
2    4920  CA-2019-160304 2019-01-02         2019-01-09  Standard Processing
3    8604  US-2019-116365 2019-01-03         2019-01-09  Standard Processing

In [6]:
order_process_data.isna().sum()

Row ID                0
Order ID              0
Order Date            0
On Truck Scan Date    0
Ship Mode             0
dtype: int64

In [7]:
order_process_data.duplicated().sum()

np.int64(0)

In [8]:
order_process_data.dtypes

Row ID                         int64
Order ID                         str
Order Date            datetime64[us]
On Truck Scan Date    datetime64[us]
Ship Mode                        str
dtype: object

In [9]:
order_process_data["Ship Mode"].unique()

<StringArray>
['Express', 'Standard Processing']
Length: 2, dtype: str

In [10]:
order_process_data["Ship Mode"].value_counts()

Ship Mode
Standard Processing    4596
Express                1303
Name: count, dtype: int64

In [11]:
order_process_data['First_class']= np.where(
    order_process_data["Ship Mode"]=='Express', 1 , 0)

In [12]:
order_process_data.tail(4)

,Row ID,Order ID,Order Date,On Truck Scan Date,Ship Mode,First_class
5895,909,CA-2020-143259,2020-12-30,2021-01-06,Standard Processing,0
5896,1297,CA-2020-115427,2020-12-30,2021-01-06,Standard Processing,0
5897,1298,CA-2020-115427,2020-12-30,2021-01-06,Standard Processing,0
5898,5092,CA-2020-156720,2020-12-30,2021-01-06,Standard Processing,0

In [13]:
order_process_data['Day_name_On_Truck_scan']=order_process_data['On Truck Scan Date'].dt.day_name()

In [14]:
order_process_data['Day_name_On_Truck_scan'].unique()

<StringArray>
['Monday', 'Wednesday', 'Friday', 'Tuesday', 'Thursday']
Length: 5, dtype: str

In [15]:
order_process_data['Day_name_On_Truck_scan'].value_counts()

Day_name_On_Truck_scan
Wednesday    3260
Friday       1377
Monday       1026
Tuesday       145
Thursday       91
Name: count, dtype: int64

In [16]:
order_process_data[(order_process_data['Day_name_On_Truck_scan'].isin(['Thursday', 'Tuesday'])) &
    (order_process_data['First_class'] == 0)
]

,Row ID,Order ID,Order Date,On Truck Scan Date,Ship Mode,First_class,Day_name_On_Truck_scan
128,8383,CA-2019-163048,2019-02-08,2019-02-19,Standard Processing,0,Tuesday
129,8842,US-2019-112396,2019-02-09,2019-02-19,Standard Processing,0,Tuesday
130,8843,US-2019-112396,2019-02-09,2019-02-19,Standard Processing,0,Tuesday
629,3531,US-2019-152835,2019-05-19,2019-05-28,Standard Processing,0,Tuesday
630,7467,CA-2019-138282,2019-05-19,2019-05-28,Standard Processing,0,Tuesday
...,...,...,...,...,...,...,...
5763,8846,CA-2020-156664,2020-12-18,2020-12-24,Standard Processing,0,Thursday
5764,8847,CA-2020-156664,2020-12-18,2020-12-24,Standard Processing,0,Thursday
5765,8848,CA-2020-156664,2020-12-18,2020-12-24,Standard Processing,0,Thursday
5766,8932,CA-2020-143252,2020-12-18,2020-12-24,Standard Processing,0,Thursday
5767,8933,CA-2020-143252,2020-12-18,2020-12-24,Standard Processing,0,Thursday

| On Truck Scan          | Meaning       |
| ---------------------- | ------------- |
| Tue/Thu + No Express   | 🚨 Suspicious |
| Expected (Mon/Wed/Fri) | ✅ Normal     |

In [17]:
order_process_data.head(3)

,Row ID,Order ID,Order Date,On Truck Scan Date,Ship Mode,First_class,Day_name_On_Truck_scan
0,3074,CA-2019-125206,2019-01-03,2019-01-07,Express,1,Monday
1,4919,CA-2019-160304,2019-01-02,2019-01-09,Standard Processing,0,Wednesday
2,4920,CA-2019-160304,2019-01-02,2019-01-09,Standard Processing,0,Wednesday

In [18]:
order_process_data["Diff_OrderDate_OnTruckScanDate"]=order_process_data["On Truck Scan Date"]-order_process_data["Order Date"]

In [19]:
order_process_data.head(3)

,Row ID,Order ID,Order Date,On Truck Scan Date,Ship Mode,First_class,Day_name_On_Truck_scan,Diff_OrderDate_OnTruckScanDate
0,3074,CA-2019-125206,2019-01-03,2019-01-07,Express,1,Monday,4 days
1,4919,CA-2019-160304,2019-01-02,2019-01-09,Standard Processing,0,Wednesday,7 days
2,4920,CA-2019-160304,2019-01-02,2019-01-09,Standard Processing,0,Wednesday,7 days

In [20]:
order_process_data["Diff_OrderDate_OnTruckScanDate"].unique()

<TimedeltaArray>
[ '4 days',  '7 days',  '6 days',  '5 days',  '1 days',  '9 days',  '8 days',
  '3 days',  '2 days', '10 days', '11 days',  '0 days', '12 days']
Length: 13, dtype: timedelta64[us]

In [22]:
order_process_data["Diff_OrderDate_OnTruckScanDate"].value_counts()

Diff_OrderDate_OnTruckScanDate
7 days     1165
8 days     1022
6 days      765
5 days      602
9 days      565
4 days      435
3 days      373
10 days     318
1 days      248
2 days      222
0 days      152
11 days      26
12 days       6
Name: count, dtype: int64

In [21]:
order_process_data.to_excel('../data/cleaned/Clean_order_process_data.xlsx',index=False)